#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J without_quadratic_IQP_Full-Pauli-CRX
#SBATCH -N 1
#SBATCH -n 36
#SBATCH --mem-per-cpu=300           # memory per cpu
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=IQP_Full-Pauli-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_Full-Pauli-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer
cd /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without/IQP_Full-Pauli-CRX

apptainer run -C -B /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without /home/gjones/projects/def-jacobsen/gjones/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without/main.py --save_path /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without/IQP_Full-Pauli-CRX  --settings /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without/IQP_Full-Pauli-CRX/IQP_Full-Pauli-CRX.json --train_set /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without/quadratic_train.bin --test_set /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without/quadratic_test.bin --scaler /home/gjones/scratch/NARVAL_FINISH/funct_specific/quadratic/error_mitigation/without/quadratic_scaler.bin >> IQP_Full-Pauli-CRX.out 2>&1

cd ..
touch IQP_Full-Pauli-CRX.done

