#! /bin/bash
#SBATCH -t 0-23:59:59
#SBATCH -J 3AL_onemore
#SBATCH -N 1
#SBATCH -n 80
#SBATCH --account=rrg-fekl-ac
#SBATCH --error=onemore.e%J        # The file where run time errors will be dumped
#SBATCH --output=onemore.o%J               # The file where the output of the terminal will be dumped


export OMP_NUM_THREADS=80
cd /scratch/j/jacobsen/gjones/16qubit/3AL/onemore
/scinet/niagara/software/2019b/opt/base/python/3.11.5/bin/python /scratch/j/jacobsen/gjones/16qubit/3AL/main.py --save_path /scratch/j/jacobsen/gjones/16qubit/3AL/onemore  --settings /scratch/j/jacobsen/gjones/16qubit/3AL/onemore/onemore.json --train_set /scratch/j/jacobsen/gjones/16qubit/3AL/PCA16_0.8_Morgan_train.bin --test_set /scratch/j/jacobsen/gjones/16qubit/3AL/PCA16_0.8_Morgan_test.bin --scaler /scratch/j/jacobsen/gjones/16qubit/3AL/PCA16_0.8_Morgan_scaler.bin --resume_file /scratch/j/jacobsen/gjones/16qubit/3AL/onemore/partial_state_model.bin > onemore.out 2>&1

cd ..
touch onemore.done

