#! /bin/bash
#SBATCH -t 0-23:59:00
#SBATCH -J M-A1-CNOT_Full-Pauli-CRX
#SBATCH -N 1
#SBATCH -n 80
#SBATCH --account=def-fekl
#SBATCH --error=M-A1-CNOT_Full-Pauli-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-A1-CNOT_Full-Pauli-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /scratch/j/jacobsen/gjones/qregress/function-calc-test/lin5qubits/M-A1-CNOT_Full-Pauli-CRX

apptainer run -C -B  ~/deb.sif /opt/miniconda/bin/python /main.py --save_path /scratch/j/jacobsen/gjones/qregress/function-calc-test/lin5qubits/M-A1-CNOT_Full-Pauli-CRX  --settings /scratch/j/jacobsen/gjones/qregress/function-calc-test/lin5qubits/M-A1-CNOT_Full-Pauli-CRX/M-A1-CNOT_Full-Pauli-CRX.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> M-A1-CNOT_Full-Pauli-CRX.out 2>&1 

cd ..
touch M-A1-CNOT_Full-Pauli-CRX.done

