#! /bin/bash
#SBATCH -t 0-23:59:00
#SBATCH -J quantum
#SBATCH -N 1
#SBATCH -n 80
#SBATCH --account=rrg-fekl-ac
#SBATCH --error=quantum.e%J        # The file where run time errors will be dumped
#SBATCH --output=quantum.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /scratch/j/jacobsen/gjones/lin5qubits/quantum

apptainer run -C -B /scratch/j/jacobsen/gjones/lin5qubits ~/deb.sif /opt/miniconda/bin/python /scratch/j/jacobsen/gjones/lin5qubits/main.py --save_path /scratch/j/jacobsen/gjones/lin5qubits/quantum  --settings /scratch/j/jacobsen/gjones/lin5qubits/quantum/quantum.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> quantum.out 2>&1 

cd ..
touch quantum.done

