#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 5_AL_PCA5_Morgan_A2_Modified-Pauli-CRX
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=260M
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2_Modified-Pauli-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2_Modified-Pauli-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL/A2_Modified-Pauli-CRX
apptainer run -C -B /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL/main.py --save_path /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL/A2_Modified-Pauli-CRX  --settings /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL/A2_Modified-Pauli-CRX/A2_Modified-Pauli-CRX.json --train_set /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL/PCA5_Morgan_train.bin --test_set /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL/PCA5_Morgan_test.bin --scaler /home/gjones/scratch/BSE_RUD_AL_test/5qubit/5_AL/PCA5_Morgan_scaler.bin >> A2_Modified-Pauli-CRX.out 2>&1 

cd ..
touch A2_Modified-Pauli-CRX.done

