#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5sine_M-M-CZ_ESU2
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CZ_ESU2.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CZ_ESU2.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/sine5qubits/M-M-CZ_ESU2
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/sine5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/sine5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/sine5qubits/M-M-CZ_ESU2  --settings /home/gjones/scratch/fivequbit_tests/sine5qubits/M-M-CZ_ESU2/M-M-CZ_ESU2.json --train_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_train.bin --test_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_test.bin --scaler /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_scaler.bin >> M-M-CZ_ESU2.out 2>&1 

cd ..
touch M-M-CZ_ESU2.done

