anyio==3.7.1
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
autograd==1.5
autoray==0.6.3
babel==2.14.0
beautifulsoup4==4.12.3
bleach==6.1.0
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
cirq==1.1.0
cirq-aqt==1.1.0
cirq-core==1.1.0
cirq-google==1.1.0
cirq-ionq==1.1.0
cirq-pasqal==1.1.0
cirq-rigetti==1.1.0
cirq-web==1.1.0
click==8.1.3
comm==0.2.2
contourpy==1.1.0
cryptography==41.0.1
cycler==0.11.0
cython==0.29.36
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
deprecated==1.2.14
dill==0.3.6
duet==0.2.8
exceptiongroup==1.1.2
executing==2.0.1
fastjsonschema==2.19.1
fonttools==4.40.0
fqdn==1.5.1
future==0.18.3
google-api-core==1.34.0
google-auth==2.21.0
googleapis-common-protos==1.59.1
grpcio==1.56.0
grpcio-status==1.48.2
h11==0.14.0
httpcore==1.0.4
httpx==0.27.0
ibm-cloud-sdk-core==3.16.7
ibm-platform-services==0.38.0
idna==3.4
importlib-metadata==7.0.2
importlib-resources==6.0.1
ipykernel==6.29.3
ipython==8.18.1
ipywidgets==8.1.2
iso8601==1.1.0
isoduration==20.11.0
jedi==0.19.1
jinja2==3.1.3
joblib==1.3.1
json5==0.9.22
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-client==8.6.1
jupyter-console==6.6.3
jupyter-core==5.7.2
jupyter-events==0.9.1
jupyter-lsp==2.2.4
jupyter-server==2.13.0
jupyter-server-terminals==0.5.3
jupyterlab==4.1.4
jupyterlab-pygments==0.3.0
jupyterlab-server==2.25.4
jupyterlab-widgets==3.0.10
kiwisolver==1.4.4
lark==0.11.3
markupsafe==2.1.5
matplotlib==3.7.2
matplotlib-inline==0.1.6
mistune==3.0.2
mitiq==0.23.0
mpmath==1.3.0
msgpack==1.0.5
mthree==2.5.1
nbclient==0.10.0
nbconvert==7.16.2
nbformat==5.10.2
nest-asyncio==1.6.0
networkx==2.8.8
notebook==7.1.1
notebook-shim==0.2.4
ntlm-auth==1.5.0
numpy==1.23.5
orjson==3.9.1
overrides==7.7.0
packaging==23.1
pandas==2.0.3
pandocfilters==1.5.1
parso==0.8.3
pbr==5.11.1
pennylane==0.31.0
pennylane-lightning==0.31.0
pennylane-qiskit==0.31.0
pennylane-qulacs==0.29.0
pexpect==4.9.0
pillow==10.0.0
platformdirs==4.2.0
ply==3.11
prometheus-client==0.20.0
prompt-toolkit==3.0.43
proto-plus==1.22.3
protobuf==3.20.3
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==1.10.11
pygments==2.17.2
pyjwt==2.7.0
pyparsing==3.0.9
pyquil==3.5.4
python-dateutil==2.8.2
python-json-logger==2.0.7
python-rapidjson==1.10
pytz==2023.3
pyyaml==6.0.1
pyzmq==25.1.0
qcs-api-client==0.21.5
qiskit==0.43.2
qiskit-aer==0.12.1
qiskit-ibm-provider==0.6.1
qiskit-ibm-runtime==0.11.1
qiskit-ibmq-provider==0.20.2
qiskit-terra==0.24.1
qtconsole==5.5.1
qtpy==2.4.1
qulacs==0.6.1
rdkit==2023.3.2
referencing==0.33.0
requests==2.31.0
requests-ntlm==1.1.0
retrying==1.3.4
rfc3339==6.2
rfc3339-validator==0.1.4
rfc3986==1.5.0
rfc3986-validator==0.1.1
rpcq==3.11.0
rpds-py==0.18.0
rsa==4.9
ruamel-yaml==0.17.32
ruamel-yaml-clib==0.2.7
rustworkx==0.13.0
scikit-learn==1.3.0
scipy==1.10.0
semantic-version==2.10.0
send2trash==1.8.2
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.5
stack-data==0.6.3
stevedore==5.1.0
symengine==0.9.2
sympy==1.12
tenacity==8.2.2
terminado==0.18.1
threadpoolctl==3.1.0
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
tornado==6.4
tqdm==4.65.0
traitlets==5.14.2
types-deprecated==1.2.9.2
types-python-dateutil==2.8.19.13
types-retry==0.9.9.3
typing-extensions==4.7.1
tzdata==2023.3
uri-template==1.3.0
urllib3==1.26.16
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
websockets==11.0.3
widgetsnbextension==4.0.10
wrapt==1.15.0
zipp==3.16.2
