#! /bin/bash
#SBATCH -t 5-00:00:00
#SBATCH -J 3_RUD_quad16qubit_M-M-CZ_Full-CRX
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --mem-per-cpu=300           # memory per cpu
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CZ_Full-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CZ_Full-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/move2narval/3_RUD_quad16qubit/M-M-CZ_Full-CRX

apptainer run -C -B /home/gjones/scratch/move2narval/3_RUD_quad16qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/move2narval/3_RUD_quad16qubit/main.py --save_path /home/gjones/scratch/move2narval/3_RUD_quad16qubit/M-M-CZ_Full-CRX  --settings /home/gjones/scratch/move2narval/3_RUD_quad16qubit/M-M-CZ_Full-CRX/M-M-CZ_Full-CRX.json --train_set /home/gjones/scratch/move2narval/3_RUD_quad16qubit/quadratic_train.bin --test_set /home/gjones/scratch/move2narval/3_RUD_quad16qubit/quadratic_test.bin --scaler /home/gjones/scratch/move2narval/3_RUD_quad16qubit/quadratic_scaler.bin >> M-M-CZ_Full-CRX.out 2>&1 

cd ..
touch M-M-CZ_Full-CRX.done

