mv -f A1-A1-CNOT_ESU2 removed/
mv -f A1-A1-CNOT_Efficient-CRX removed/
mv -f A1-A1-CNOT_Efficient-CRZ removed/
mv -f A1-A1-CNOT_Full-CRX removed/
mv -f A1-A1-CNOT_Full-CRZ removed/
mv -f A1-A1-CZ_ESU2 removed/
mv -f A1-A1-CZ_Efficient-CRX removed/
mv -f A1-A1-CZ_Efficient-CRZ removed/
mv -f A1-A1-CZ_Full-CRX removed/
mv -f A1-A1-CZ_Full-CRZ removed/
mv -f A1_ESU2 removed/
mv -f A1_Efficient-CRX removed/
mv -f A1_Efficient-CRZ removed/
mv -f A1_Full-CRX removed/
mv -f A1_Full-CRZ removed/
mv -f A2-A2-CNOT_ESU2 removed/
mv -f A2-A2-CNOT_Efficient-CRX removed/
mv -f A2-A2-CNOT_Efficient-CRZ removed/
mv -f A2-A2-CNOT_Full-CRX removed/
mv -f A2-A2-CNOT_Full-CRZ removed/
mv -f A2-A2-CZ_ESU2 removed/
mv -f A2-A2-CZ_Efficient-CRX removed/
mv -f A2-A2-CZ_Efficient-CRZ removed/
mv -f A2-A2-CZ_Full-CRX removed/
mv -f A2-A2-CZ_Full-CRZ removed/
mv -f A2_ESU2 removed/
mv -f A2_Efficient-CRX removed/
mv -f A2_Efficient-CRZ removed/
mv -f A2_Full-CRX removed/
mv -f A2_Full-CRZ removed/
mv -f IQP_ESU2 removed/
mv -f IQP_Efficient-CRX removed/
mv -f IQP_Efficient-CRZ removed/
mv -f IQP_Full-CRX removed/
mv -f IQP_Full-CRZ removed/
mv -f M-A1-CNOT_ESU2 removed/
mv -f M-A1-CNOT_Efficient-CRX removed/
mv -f M-A1-CNOT_Efficient-CRZ removed/
mv -f M-A1-CNOT_Full-CRX removed/
mv -f M-A1-CNOT_Full-CRZ removed/
mv -f M-A1-CZ_ESU2 removed/
mv -f M-A1-CZ_Efficient-CRX removed/
mv -f M-A1-CZ_Efficient-CRZ removed/
mv -f M-A1-CZ_Full-CRX removed/
mv -f M-A1-CZ_Full-CRZ removed/
mv -f M-A2-CNOT_ESU2 removed/
mv -f M-A2-CNOT_Efficient-CRX removed/
mv -f M-A2-CNOT_Efficient-CRZ removed/
mv -f M-A2-CNOT_Full-CRX removed/
mv -f M-A2-CNOT_Full-CRZ removed/
mv -f M-A2-CZ_ESU2 removed/
mv -f M-A2-CZ_Efficient-CRX removed/
mv -f M-A2-CZ_Efficient-CRZ removed/
mv -f M-A2-CZ_Full-CRX removed/
mv -f M-A2-CZ_Full-CRZ removed/
mv -f M-M-CNOT_ESU2 removed/
mv -f M-M-CNOT_Efficient-CRX removed/
mv -f M-M-CNOT_Efficient-CRZ removed/
mv -f M-M-CNOT_Full-CRX removed/
mv -f M-M-CNOT_Full-CRZ removed/
mv -f M-M-CZ_ESU2 removed/
mv -f M-M-CZ_Efficient-CRX removed/
mv -f M-M-CZ_Efficient-CRZ removed/
mv -f M-M-CZ_Full-CRX removed/
mv -f M-M-CZ_Full-CRZ removed/
mv -f M_ESU2 removed/
mv -f M_Efficient-CRX removed/
mv -f M_Efficient-CRZ removed/
mv -f M_Full-CRX removed/
mv -f M_Full-CRZ removed/
