sbatch A1-A1-CNOT_Efficient-CRX.sub
sbatch A1-A1-CNOT_HWE-CNOT.sub
sbatch A1-A1-CNOT_HWE-CZ.sub
sbatch A1-A1-CZ_HWE-CNOT.sub
sbatch A1-A1-CZ_HWE-CZ.sub
sbatch A1_HWE-CNOT.sub
sbatch A1_HWE-CZ.sub
sbatch A2-A2-CNOT_HWE-CNOT.sub
sbatch A2-A2-CNOT_HWE-CZ.sub
sbatch A2-A2-CZ_HWE-CNOT.sub
sbatch A2-A2-CZ_HWE-CZ.sub
sbatch A2_HWE-CNOT.sub
sbatch A2_HWE-CZ.sub
sbatch IQP_HWE-CNOT.sub
sbatch IQP_HWE-CZ.sub
sbatch M-A1-CNOT_HWE-CNOT.sub
sbatch M-A1-CNOT_HWE-CZ.sub
sbatch M-A1-CZ_HWE-CNOT.sub
sbatch M-A1-CZ_HWE-CZ.sub
sbatch M-A2-CNOT_HWE-CNOT.sub
sbatch M-A2-CNOT_HWE-CZ.sub
sbatch M-A2-CZ_HWE-CNOT.sub
sbatch M-A2-CZ_HWE-CZ.sub
sbatch M-M-CNOT_HWE-CNOT.sub
sbatch M-M-CNOT_HWE-CZ.sub
sbatch M-M-CZ_HWE-CNOT.sub
sbatch M-M-CZ_HWE-CZ.sub
sbatch M_HWE-CNOT.sub
sbatch M_HWE-CZ.sub
