#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 3AL_PCA5_Morgan_A2_HWE-CNOT
#SBATCH -N 1
#SBATCH -n 64
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2_HWE-CNOT.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2_HWE-CNOT.o%J               # The file where the output of the terminal will be dumped

cd /home/gjones/scratch/RUD_AL/3AL/A2_HWE-CNOT

/lustre06/project/6006115/gjones/env/bin/python3 /home/gjones/scratch/RUD_AL/3AL/main.py --save_path /home/gjones/scratch/RUD_AL/3AL/A2_HWE-CNOT  --settings /home/gjones/scratch/RUD_AL/3AL/A2_HWE-CNOT/A2_HWE-CNOT.json --train_set /home/gjones/scratch/RUD_AL/3AL/PCA5_Morgan_train.bin --test_set /home/gjones/scratch/RUD_AL/3AL/PCA5_Morgan_test.bin --scaler /home/gjones/scratch/RUD_AL/3AL/PCA5_Morgan_scaler.bin > A2_HWE-CNOT.out 2>&1

cd ..
touch A2_HWE-CNOT.done

