#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J PCA16_Morgan_A1-A1-CZ_Efficient-CRZ
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1-A1-CZ_Efficient-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1-A1-CZ_Efficient-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE-calc-test/16qubit/A1-A1-CZ_Efficient-CRZ
apptainer run -C -B /home/gjones/scratch/BSE-calc-test/16qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE-calc-test/16qubit/main.py --save_path /home/gjones/scratch/BSE-calc-test/16qubit/A1-A1-CZ_Efficient-CRZ  --settings /home/gjones/scratch/BSE-calc-test/16qubit/A1-A1-CZ_Efficient-CRZ/A1-A1-CZ_Efficient-CRZ.json --train_set /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_train.bin --test_set /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_test.bin --scaler /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_scaler.bin >> A1-A1-CZ_Efficient-CRZ.out 2>&1 

cd ..
touch A1-A1-CZ_Efficient-CRZ.done

