mv -f ./M-A1-CZ_ESU2 finished
mv -f ./M-M-CNOT_Efficient-CRZ finished
mv -f ./M-A2-CNOT_Efficient-CRZ finished
mv -f ./M-M-CNOT_ESU2 finished
mv -f ./M-A2-CZ_Efficient-CRZ finished
mv -f ./A1_Efficient-CRX finished
mv -f ./M_Efficient-CRX finished
mv -f ./M-M-CZ_ESU2 finished
mv -f ./M-A1-CNOT_Full-CRZ finished
mv -f ./A1-A1-CZ_Full-CRX finished
mv -f ./A1-A1-CNOT_Full-CRZ finished
mv -f ./A1-A1-CZ_Efficient-CRX finished
mv -f ./A2-A2-CNOT_Efficient-CRX finished
mv -f ./M-A1-CZ_Efficient-CRZ finished
mv -f ./M_Full-CRX finished
mv -f ./A1_Full-CRX finished
mv -f ./A2_Full-CRZ finished
mv -f ./A1-A1-CNOT_Efficient-CRX finished
mv -f ./A2-A2-CZ_Efficient-CRX finished
mv -f ./IQP_ESU2 finished
mv -f ./IQP_Full-CRZ finished
