#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J PCA16_Morgan_IQP_Full-Pauli-CRX
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=IQP_Full-Pauli-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_Full-Pauli-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE-calc-test/16qubit/IQP_Full-Pauli-CRX
apptainer run -C -B /home/gjones/scratch/BSE-calc-test/16qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE-calc-test/16qubit/main.py --save_path /home/gjones/scratch/BSE-calc-test/16qubit/IQP_Full-Pauli-CRX  --settings /home/gjones/scratch/BSE-calc-test/16qubit/IQP_Full-Pauli-CRX/IQP_Full-Pauli-CRX.json --train_set /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_train.bin --test_set /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_test.bin --scaler /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_scaler.bin >> IQP_Full-Pauli-CRX.out 2>&1 

cd ..
touch IQP_Full-Pauli-CRX.done

