#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J PCA16_Morgan_M-M-CNOT_ESU2
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CNOT_ESU2.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CNOT_ESU2.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE-calc-test/16qubit/M-M-CNOT_ESU2
apptainer run -C -B /home/gjones/scratch/BSE-calc-test/16qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE-calc-test/16qubit/main.py --save_path /home/gjones/scratch/BSE-calc-test/16qubit/M-M-CNOT_ESU2  --settings /home/gjones/scratch/BSE-calc-test/16qubit/M-M-CNOT_ESU2/M-M-CNOT_ESU2.json --train_set /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_train.bin --test_set /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_test.bin --scaler /home/gjones/scratch/BSE-calc-test/16qubit/PCA16_Morgan_scaler.bin >> M-M-CNOT_ESU2.out 2>&1 

cd ..
touch M-M-CNOT_ESU2.done

