#! /bin/bash
#SBATCH -t 1-00:00:00
#SBATCH -J A2-A2-CNOT_HWE-CZ
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2-A2-CNOT_HWE-CZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2-A2-CNOT_HWE-CZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/lin5qubits/A2-A2-CNOT_HWE-CZ

apptainer run -C -B /home/gjones/scratch/fivequbit_tests/lin5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/lin5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/lin5qubits/A2-A2-CNOT_HWE-CZ  --settings /home/gjones/scratch/fivequbit_tests/lin5qubits/A2-A2-CNOT_HWE-CZ/A2-A2-CNOT_HWE-CZ.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> A2-A2-CNOT_HWE-CZ.out 2>&1 

cd ..
touch A2-A2-CNOT_HWE-CZ.done

