#! /bin/bash
#SBATCH -t 1-00:00:00
#SBATCH -J M-M-CNOT_Hadamard
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CNOT_Hadamard.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CNOT_Hadamard.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/lin5qubits/M-M-CNOT_Hadamard

apptainer run -C -B /home/gjones/scratch/fivequbit_tests/lin5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/lin5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/lin5qubits/M-M-CNOT_Hadamard  --settings /home/gjones/scratch/fivequbit_tests/lin5qubits/M-M-CNOT_Hadamard/M-M-CNOT_Hadamard.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> M-M-CNOT_Hadamard.out 2>&1 

cd ..
touch M-M-CNOT_Hadamard.done

