#! /bin/bash
#SBATCH -t 1-00:00:00
#SBATCH -J quantum
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=quantum.e%J        # The file where run time errors will be dumped
#SBATCH --output=quantum.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/lin5qubits/quantum

apptainer run -C -B /home/gjones/scratch/fivequbit_tests/lin5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/lin5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/lin5qubits/quantum  --settings /home/gjones/scratch/fivequbit_tests/lin5qubits/quantum/quantum.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> quantum.out 2>&1 

cd ..
touch quantum.done

