#! /bin/bash
#SBATCH -t 5-00:00:00
#SBATCH -J 5_AL_sin16qubit_M-M-CZ_Full-CRZ
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --mem-per-cpu=300           # memory per cpu
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CZ_Full-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CZ_Full-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/move2narval/5_AL_sin16qubit/M-M-CZ_Full-CRZ

apptainer run -C -B /home/gjones/scratch/move2narval/5_AL_sin16qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/move2narval/5_AL_sin16qubit/main.py --save_path /home/gjones/scratch/move2narval/5_AL_sin16qubit/M-M-CZ_Full-CRZ  --settings /home/gjones/scratch/move2narval/5_AL_sin16qubit/M-M-CZ_Full-CRZ/M-M-CZ_Full-CRZ.json --train_set /home/gjones/scratch/move2narval/5_AL_sin16qubit/sine_train.bin --test_set /home/gjones/scratch/move2narval/5_AL_sin16qubit/sine_test.bin --scaler /home/gjones/scratch/move2narval/5_AL_sin16qubit/sine_scaler.bin >> M-M-CZ_Full-CRZ.out 2>&1 

cd ..
touch M-M-CZ_Full-CRZ.done

