#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J PCA5_Morgan_A2-A2-CZ_Full-CRZ
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2-A2-CZ_Full-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2-A2-CZ_Full-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE-calc-test/5qubit/A2-A2-CZ_Full-CRZ
apptainer run -C -B /home/gjones/scratch/BSE-calc-test/5qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE-calc-test/5qubit/main.py --save_path /home/gjones/scratch/BSE-calc-test/5qubit/A2-A2-CZ_Full-CRZ  --settings /home/gjones/scratch/BSE-calc-test/5qubit/A2-A2-CZ_Full-CRZ/A2-A2-CZ_Full-CRZ.json --train_set /home/gjones/scratch/BSE-calc-test/5qubit/PCA5_Morgan_train.bin --test_set /home/gjones/scratch/BSE-calc-test/5qubit/PCA5_Morgan_test.bin --scaler /home/gjones/scratch/BSE-calc-test/5qubit/PCA5_Morgan_scaler.bin >> A2-A2-CZ_Full-CRZ.out 2>&1 

cd ..
touch A2-A2-CZ_Full-CRZ.done

