#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J TREX_linear_IQP_Full-Pauli-CRZ
#SBATCH -N 1
#SBATCH -n 36
#SBATCH --mem-per-cpu=300           # memory per cpu
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=IQP_Full-Pauli-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_Full-Pauli-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer
cd /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX/IQP_Full-Pauli-CRZ

apptainer run -C -B /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX /home/gjones/projects/def-jacobsen/gjones/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX/main.py --save_path /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX/IQP_Full-Pauli-CRZ  --settings /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX/IQP_Full-Pauli-CRZ/IQP_Full-Pauli-CRZ.json --train_set /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX/linear_train.bin --test_set /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX/linear_test.bin --scaler /home/gjones/scratch/NARVAL_FINISH/funct_specific/linear/error_mitigation/TREX/linear_scaler.bin >> IQP_Full-Pauli-CRZ.out 2>&1

cd ..
touch IQP_Full-Pauli-CRZ.done

