#! /bin/bash
#SBATCH -t 0-23:59:59
#SBATCH -J 3RUD_PCA5_Morgan_A2_HWE-CNOT
#SBATCH -N 1
#SBATCH -n 64
#SBATCH --account=rrg-fekl-ac
#SBATCH --error=A2_HWE-CNOT.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2_HWE-CNOT.o%J               # The file where the output of the terminal will be dumped

module load apptainer
cd /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD/A2_HWE-CNOT


apptainer run -C -B /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD /home/j/jacobsen/gjones/deb.sif /opt/miniconda/bin/python /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD/main.py --save_path /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD/A2_HWE-CNOT  --settings /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD/A2_HWE-CNOT/A2_HWE-CNOT.json --train_set /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD/PCA5_Morgan_train.bin --test_set /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD/PCA5_Morgan_test.bin --scaler /scratch/j/jacobsen/gjones/BSE5_func_specific/RUD_AL/3RUD/PCA5_Morgan_scaler.bin > A2_HWE-CNOT.out 2>&1


cd ..
touch A2_HWE-CNOT.done

