#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 5_AL_PCA16_Morgan_M-M-CZ_Modified-Pauli-CRZ
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=260M
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CZ_Modified-Pauli-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CZ_Modified-Pauli-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL/M-M-CZ_Modified-Pauli-CRZ
apptainer run -C -B /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL/main.py --save_path /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL/M-M-CZ_Modified-Pauli-CRZ  --settings /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL/M-M-CZ_Modified-Pauli-CRZ/M-M-CZ_Modified-Pauli-CRZ.json --train_set /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL/PCA16_Morgan_train.bin --test_set /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL/PCA16_Morgan_test.bin --scaler /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_AL/PCA16_Morgan_scaler.bin >> M-M-CZ_Modified-Pauli-CRZ.out 2>&1 

cd ..
touch M-M-CZ_Modified-Pauli-CRZ.done

