#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5quadratic_A1-A1-CNOT_Hadamard
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1-A1-CNOT_Hadamard.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1-A1-CNOT_Hadamard.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/quad5qubits/A1-A1-CNOT_Hadamard
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/quad5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/quad5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/quad5qubits/A1-A1-CNOT_Hadamard  --settings /home/gjones/scratch/fivequbit_tests/quad5qubits/A1-A1-CNOT_Hadamard/A1-A1-CNOT_Hadamard.json --train_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_train.bin --test_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_test.bin --scaler /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_scaler.bin >> A1-A1-CNOT_Hadamard.out 2>&1 

cd ..
touch A1-A1-CNOT_Hadamard.done

