#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5quadratic_A1_HWE-CNOT
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1_HWE-CNOT.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1_HWE-CNOT.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/quad5qubits/A1_HWE-CNOT
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/quad5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/quad5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/quad5qubits/A1_HWE-CNOT  --settings /home/gjones/scratch/fivequbit_tests/quad5qubits/A1_HWE-CNOT/A1_HWE-CNOT.json --train_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_train.bin --test_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_test.bin --scaler /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_scaler.bin >> A1_HWE-CNOT.out 2>&1 

cd ..
touch A1_HWE-CNOT.done

