#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 3_AL_PCA5_Morgan_M-M-CZ_Efficient-CRX
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=260M
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CZ_Efficient-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CZ_Efficient-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL/M-M-CZ_Efficient-CRX
apptainer run -C -B /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL/main.py --save_path /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL/M-M-CZ_Efficient-CRX  --settings /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL/M-M-CZ_Efficient-CRX/M-M-CZ_Efficient-CRX.json --train_set /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL/PCA5_Morgan_train.bin --test_set /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL/PCA5_Morgan_test.bin --scaler /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_AL/PCA5_Morgan_scaler.bin >> M-M-CZ_Efficient-CRX.out 2>&1 

cd ..
touch M-M-CZ_Efficient-CRX.done

