#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 3_RUD_PCA16_Morgan_M-A2-CZ_ESU2
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=260M
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-A2-CZ_ESU2.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-A2-CZ_ESU2.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD/M-A2-CZ_ESU2
apptainer run -C -B /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD/main.py --save_path /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD/M-A2-CZ_ESU2  --settings /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD/M-A2-CZ_ESU2/M-A2-CZ_ESU2.json --train_set /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD/PCA16_Morgan_train.bin --test_set /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD/PCA16_Morgan_test.bin --scaler /home/gjones/scratch/BSE_RUD_AL_test/16qubit/3_RUD/PCA16_Morgan_scaler.bin >> M-A2-CZ_ESU2.out 2>&1 

cd ..
touch M-A2-CZ_ESU2.done

