#!/bin/bash
cp -r ./A1-A1-CNOT_ESU2 ./move
cp -r ./A1-A1-CNOT_Efficient-CRX ./move
cp -r ./A1-A1-CNOT_Efficient-CRZ ./move
cp -r ./A1-A1-CNOT_Full-CRX ./move
cp -r ./A1-A1-CNOT_Full-CRZ ./move
cp -r ./A1-A1-CNOT_Full-Pauli-CRX ./move
cp -r ./A1-A1-CNOT_Full-Pauli-CRZ ./move
cp -r ./A1-A1-CNOT_HWE-CNOT ./move
cp -r ./A1-A1-CNOT_HWE-CZ ./move
cp -r ./A1-A1-CNOT_Hadamard ./move
cp -r ./A1-A1-CZ_ESU2 ./move
cp -r ./A1-A1-CZ_Efficient-CRX ./move
cp -r ./A1-A1-CZ_Efficient-CRZ ./move
cp -r ./A1-A1-CZ_Full-CRX ./move
cp -r ./A1-A1-CZ_Full-CRZ ./move
cp -r ./A1-A1-CZ_Full-Pauli-CRX ./move
cp -r ./A1-A1-CZ_Full-Pauli-CRZ ./move
cp -r ./A1-A1-CZ_HWE-CNOT ./move
cp -r ./A1-A1-CZ_HWE-CZ ./move
cp -r ./A1-A1-CZ_Hadamard ./move
cp -r ./A1_ESU2 ./move
cp -r ./A1_Efficient-CRX ./move
cp -r ./A1_Efficient-CRZ ./move
cp -r ./A1_Full-CRX ./move
cp -r ./A1_Full-CRZ ./move
cp -r ./A1_Full-Pauli-CRX ./move
cp -r ./A1_Full-Pauli-CRZ ./move
cp -r ./A1_HWE-CNOT ./move
cp -r ./A1_HWE-CZ ./move
cp -r ./A1_Hadamard ./move
cp -r ./A2-A2-CNOT_ESU2 ./move
cp -r ./A2-A2-CNOT_Efficient-CRX ./move
cp -r ./A2-A2-CNOT_Efficient-CRZ ./move
cp -r ./A2-A2-CNOT_Full-CRX ./move
cp -r ./A2-A2-CNOT_Full-CRZ ./move
cp -r ./A2-A2-CNOT_Full-Pauli-CRX ./move
cp -r ./A2-A2-CNOT_Full-Pauli-CRZ ./move
cp -r ./A2-A2-CNOT_HWE-CNOT ./move
cp -r ./A2-A2-CNOT_HWE-CZ ./move
cp -r ./A2-A2-CNOT_Hadamard ./move
cp -r ./A2-A2-CZ_ESU2 ./move
cp -r ./A2-A2-CZ_Efficient-CRX ./move
cp -r ./A2-A2-CZ_Efficient-CRZ ./move
cp -r ./A2-A2-CZ_Full-CRX ./move
cp -r ./A2-A2-CZ_Full-CRZ ./move
cp -r ./A2-A2-CZ_Full-Pauli-CRX ./move
cp -r ./A2-A2-CZ_Full-Pauli-CRZ ./move
cp -r ./A2-A2-CZ_HWE-CNOT ./move
cp -r ./A2-A2-CZ_HWE-CZ ./move
cp -r ./A2-A2-CZ_Hadamard ./move
cp -r ./A2_ESU2 ./move
cp -r ./A2_Efficient-CRX ./move
cp -r ./A2_Efficient-CRZ ./move
cp -r ./A2_Full-CRX ./move
cp -r ./A2_Full-CRZ ./move
cp -r ./A2_Full-Pauli-CRX ./move
cp -r ./A2_Full-Pauli-CRZ ./move
cp -r ./A2_HWE-CNOT ./move
cp -r ./A2_HWE-CZ ./move
cp -r ./A2_Hadamard ./move
cp -r ./IQP_ESU2 ./move
cp -r ./IQP_Efficient-CRX ./move
cp -r ./IQP_Efficient-CRZ ./move
cp -r ./IQP_Full-CRX ./move
cp -r ./IQP_Full-CRZ ./move
cp -r ./IQP_Full-Pauli-CRX ./move
cp -r ./IQP_Full-Pauli-CRZ ./move
cp -r ./IQP_HWE-CNOT ./move
cp -r ./IQP_HWE-CZ ./move
cp -r ./IQP_Hadamard ./move
cp -r ./M-A1-CNOT_ESU2 ./move
cp -r ./M-A1-CNOT_Efficient-CRX ./move
cp -r ./M-A1-CNOT_Efficient-CRZ ./move
cp -r ./M-A1-CNOT_Full-CRX ./move
cp -r ./M-A1-CNOT_Full-CRZ ./move
cp -r ./M-A1-CNOT_Full-Pauli-CRX ./move
cp -r ./M-A1-CNOT_Full-Pauli-CRZ ./move
cp -r ./M-A1-CNOT_HWE-CNOT ./move
cp -r ./M-A1-CNOT_HWE-CZ ./move
cp -r ./M-A1-CNOT_Hadamard ./move
cp -r ./M-A1-CZ_ESU2 ./move
cp -r ./M-A1-CZ_Efficient-CRX ./move
cp -r ./M-A1-CZ_Efficient-CRZ ./move
cp -r ./M-A1-CZ_Full-CRX ./move
cp -r ./M-A1-CZ_Full-CRZ ./move
cp -r ./M-A1-CZ_Full-Pauli-CRX ./move
cp -r ./M-A1-CZ_Full-Pauli-CRZ ./move
cp -r ./M-A1-CZ_HWE-CNOT ./move
cp -r ./M-A1-CZ_HWE-CZ ./move
cp -r ./M-A1-CZ_Hadamard ./move
cp -r ./M-A2-CNOT_ESU2 ./move
cp -r ./M-A2-CNOT_Efficient-CRX ./move
cp -r ./M-A2-CNOT_Efficient-CRZ ./move
cp -r ./M-A2-CNOT_Full-CRX ./move
cp -r ./M-A2-CNOT_Full-CRZ ./move
cp -r ./M-A2-CNOT_Full-Pauli-CRX ./move
cp -r ./M-A2-CNOT_Full-Pauli-CRZ ./move
cp -r ./M-A2-CNOT_HWE-CNOT ./move
cp -r ./M-A2-CNOT_HWE-CZ ./move
cp -r ./M-A2-CNOT_Hadamard ./move
cp -r ./M-A2-CZ_ESU2 ./move
cp -r ./M-A2-CZ_Efficient-CRX ./move
cp -r ./M-A2-CZ_Efficient-CRZ ./move
cp -r ./M-A2-CZ_Full-CRX ./move
cp -r ./M-A2-CZ_Full-CRZ ./move
cp -r ./M-A2-CZ_Full-Pauli-CRX ./move
cp -r ./M-A2-CZ_Full-Pauli-CRZ ./move
cp -r ./M-A2-CZ_HWE-CNOT ./move
cp -r ./M-A2-CZ_HWE-CZ ./move
cp -r ./M-A2-CZ_Hadamard ./move
cp -r ./M-M-CNOT_ESU2 ./move
cp -r ./M-M-CNOT_Efficient-CRX ./move
cp -r ./M-M-CNOT_Efficient-CRZ ./move
cp -r ./M-M-CNOT_Full-CRX ./move
cp -r ./M-M-CNOT_Full-CRZ ./move
cp -r ./M-M-CNOT_Full-Pauli-CRX ./move
cp -r ./M-M-CNOT_Full-Pauli-CRZ ./move
cp -r ./M-M-CNOT_HWE-CNOT ./move
cp -r ./M-M-CNOT_HWE-CZ ./move
cp -r ./M-M-CNOT_Hadamard ./move
cp -r ./M-M-CZ_ESU2 ./move
cp -r ./M-M-CZ_Efficient-CRX ./move
cp -r ./M-M-CZ_Efficient-CRZ ./move
cp -r ./M-M-CZ_Full-CRX ./move
cp -r ./M-M-CZ_Full-CRZ ./move
cp -r ./M-M-CZ_Full-Pauli-CRX ./move
cp -r ./M-M-CZ_Full-Pauli-CRZ ./move
cp -r ./M-M-CZ_HWE-CNOT ./move
cp -r ./M-M-CZ_HWE-CZ ./move
cp -r ./M-M-CZ_Hadamard ./move
cp -r ./M_ESU2 ./move
cp -r ./M_Efficient-CRX ./move
cp -r ./M_Efficient-CRZ ./move
cp -r ./M_Full-CRX ./move
cp -r ./M_Full-CRZ ./move
cp -r ./M_Full-Pauli-CRX ./move
cp -r ./M_Full-Pauli-CRZ ./move
cp -r ./M_HWE-CNOT ./move
cp -r ./M_HWE-CZ ./move
cp -r ./M_Hadamard ./move
