rm -rf  ./A1-A1-CNOT_ESU2
rm -rf  ./A1-A1-CNOT_Efficient-CRX
rm -rf  ./A1-A1-CNOT_Efficient-CRZ
rm -rf  ./A1-A1-CNOT_Full-CRX
rm -rf  ./A1-A1-CNOT_Full-CRZ
rm -rf  ./A1-A1-CZ_ESU2
rm -rf  ./A1-A1-CZ_Efficient-CRX
rm -rf  ./A1-A1-CZ_Efficient-CRZ
rm -rf  ./A1-A1-CZ_Full-CRX
rm -rf  ./A1-A1-CZ_Full-CRZ
rm -rf  ./A1_ESU2
rm -rf  ./A1_Efficient-CRX
rm -rf  ./A1_Efficient-CRZ
rm -rf  ./A1_Full-CRX
rm -rf  ./A1_Full-CRZ
rm -rf  ./A2-A2-CNOT_ESU2
rm -rf  ./A2-A2-CNOT_Efficient-CRX
rm -rf  ./A2-A2-CNOT_Efficient-CRZ
rm -rf  ./A2-A2-CNOT_Full-CRX
rm -rf  ./A2-A2-CNOT_Full-CRZ
rm -rf  ./A2-A2-CZ_ESU2
rm -rf  ./A2-A2-CZ_Efficient-CRX
rm -rf  ./A2-A2-CZ_Efficient-CRZ
rm -rf  ./A2-A2-CZ_Full-CRX
rm -rf  ./A2-A2-CZ_Full-CRZ
rm -rf  ./A2_ESU2
rm -rf  ./A2_Efficient-CRX
rm -rf  ./A2_Efficient-CRZ
rm -rf  ./A2_Full-CRX
rm -rf  ./A2_Full-CRZ
rm -rf  ./IQP_ESU2
rm -rf  ./IQP_Efficient-CRX
rm -rf  ./IQP_Efficient-CRZ
rm -rf  ./IQP_Full-CRX
rm -rf  ./IQP_Full-CRZ
rm -rf  ./M-A1-CNOT_ESU2
rm -rf  ./M-A1-CNOT_Efficient-CRX
rm -rf  ./M-A1-CNOT_Efficient-CRZ
rm -rf  ./M-A1-CNOT_Full-CRX
rm -rf  ./M-A1-CNOT_Full-CRZ
rm -rf  ./M-A1-CZ_ESU2
rm -rf  ./M-A1-CZ_Efficient-CRX
rm -rf  ./M-A1-CZ_Efficient-CRZ
rm -rf  ./M-A1-CZ_Full-CRX
rm -rf  ./M-A1-CZ_Full-CRZ
rm -rf  ./M-A2-CNOT_ESU2
rm -rf  ./M-A2-CNOT_Efficient-CRX
rm -rf  ./M-A2-CNOT_Efficient-CRZ
rm -rf  ./M-A2-CNOT_Full-CRX
rm -rf  ./M-A2-CNOT_Full-CRZ
rm -rf  ./M-A2-CZ_ESU2
rm -rf  ./M-A2-CZ_Efficient-CRX
rm -rf  ./M-A2-CZ_Efficient-CRZ
rm -rf  ./M-A2-CZ_Full-CRX
rm -rf  ./M-A2-CZ_Full-CRZ
rm -rf  ./M-M-CNOT_ESU2
rm -rf  ./M-M-CNOT_Efficient-CRX
rm -rf  ./M-M-CNOT_Efficient-CRZ
rm -rf  ./M-M-CNOT_Full-CRX
rm -rf  ./M-M-CNOT_Full-CRZ
rm -rf  ./M-M-CZ_ESU2
rm -rf  ./M-M-CZ_Efficient-CRX
rm -rf  ./M-M-CZ_Efficient-CRZ
rm -rf  ./M-M-CZ_Full-CRX
rm -rf  ./M-M-CZ_Full-CRZ
rm -rf  ./M_ESU2
rm -rf  ./M_Efficient-CRX
rm -rf  ./M_Efficient-CRZ
rm -rf  ./M_Full-CRX
rm -rf  ./M_Full-CRZ
