#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 5_RUD_PCA16_Morgan_A2-A2-CNOT_HWE-CZ
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=260M
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2-A2-CNOT_HWE-CZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2-A2-CNOT_HWE-CZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD/A2-A2-CNOT_HWE-CZ
apptainer run -C -B /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD/main.py --save_path /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD/A2-A2-CNOT_HWE-CZ  --settings /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD/A2-A2-CNOT_HWE-CZ/A2-A2-CNOT_HWE-CZ.json --train_set /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD/PCA16_Morgan_train.bin --test_set /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD/PCA16_Morgan_test.bin --scaler /home/gjones/scratch/BSE_RUD_AL_test/16qubit/5_RUD/PCA16_Morgan_scaler.bin >> A2-A2-CNOT_HWE-CZ.out 2>&1 

cd ..
touch A2-A2-CNOT_HWE-CZ.done

