mv -f  ./A2_HWE-CNOT finished/
mv -f  ./M_Modified-Pauli-CRX finished/
mv -f  ./M-M-CZ_Modified-Pauli-CRX finished/
mv -f  ./M_Full-Pauli-CRZ finished/
mv -f  ./M-A2-CZ_Hadamard finished/
mv -f  ./A1-A1-CZ_Modified-Pauli-CRZ finished/
mv -f  ./IQP_Full-Pauli-CRZ finished/
mv -f  ./IQP_HWE-CNOT finished/
mv -f  ./A2_Full-Pauli-CRX finished/
mv -f  ./A2_Modified-Pauli-CRZ finished/
mv -f  ./IQP_HWE-CZ finished/
mv -f  ./M-M-CZ_HWE-CZ finished/
mv -f  ./M-A1-CZ_Modified-Pauli-CRZ finished/
mv -f  ./A2-A2-CZ_Modified-Pauli-CRX finished/
mv -f  ./M-A2-CNOT_Full-Pauli-CRX finished/
mv -f  ./IQP_Hadamard finished/
mv -f  ./M-A2-CZ_Modified-Pauli-CRX finished/
mv -f  ./M_HWE-CZ finished/
mv -f  ./M-A1-CNOT_Modified-Pauli-CRX finished/
mv -f  ./IQP_Modified-Pauli-CRZ finished/
mv -f  ./A2_Hadamard finished/
mv -f  ./M-M-CNOT_Modified-Pauli-CRX finished/
mv -f  ./M-A2-CZ_HWE-CNOT finished/
mv -f  ./M-A2-CNOT_Modified-Pauli-CRX finished/
mv -f  ./M-A2-CZ_Full-Pauli-CRZ finished/
mv -f  ./A1_Modified-Pauli-CRX finished/
mv -f  ./M-A1-CNOT_HWE-CNOT finished/
mv -f  ./A1_Full-Pauli-CRZ finished/
mv -f  ./A2-A2-CNOT_Modified-Pauli-CRX finished/
mv -f  ./A1-A1-CNOT_Hadamard finished/
mv -f  ./M-A1-CNOT_Efficient-CRX finished/
mv -f  ./M-M-CZ_Full-Pauli-CRZ finished/
mv -f  ./A1-A1-CZ_Full-Pauli-CRX finished/
mv -f  ./A2-A2-CZ_Full-Pauli-CRX finished/
mv -f  ./M-A1-CNOT_Hadamard finished/
mv -f  ./A2-A2-CZ_Full-CRX finished/
mv -f  ./M-A1-CZ_Full-Pauli-CRX finished/
mv -f  ./A1-A1-CNOT_Modified-Pauli-CRX finished/
mv -f  ./A2-A2-CNOT_Full-CRX finished/
mv -f  ./M-A2-CNOT_Full-CRX finished/
mv -f  ./M-M-CNOT_Full-CRX finished/
mv -f  ./IQP_Efficient-CRX finished/
mv -f  ./A1-A1-CNOT_HWE-CNOT finished/
mv -f  ./A2-A2-CNOT_Full-Pauli-CRX finished/
mv -f  ./M-M-CNOT_Full-Pauli-CRZ finished/
mv -f  ./A1_HWE-CZ finished/
mv -f  ./A1_ESU2 finished/
mv -f  ./M-M-CZ_Efficient-CRX finished/
mv -f  ./M-A2-CZ_Full-CRZ finished/
mv -f  ./M-A1-CZ_Full-CRX finished/
mv -f  ./M-M-CZ_Full-CRX finished/
mv -f  ./A1-A1-CNOT_Full-Pauli-CRX finished/
mv -f  ./A2_Efficient-CRZ finished/
mv -f  ./M-A2-CNOT_HWE-CZ finished/
mv -f  ./M-A1-CNOT_Full-Pauli-CRX finished/
mv -f  ./M-A1-CZ_Full-CRZ finished/
mv -f  ./M-A2-CZ_Full-CRX finished/
mv -f  ./A2-A2-CNOT_ESU2 finished/
mv -f  ./M_HWE-CNOT finished/
mv -f  ./M-M-CNOT_HWE-CZ finished/
mv -f  ./M-A1-CNOT_ESU2 finished/
mv -f  ./M-M-CNOT_Full-Pauli-CRX finished/
mv -f  ./M-M-CZ_Efficient-CRZ finished/
mv -f  ./M-A1-CNOT_Full-Pauli-CRZ finished/
mv -f  ./A2_HWE-CZ finished/
mv -f  ./M-A2-CZ_HWE-CZ finished/
mv -f  ./A1-A1-CNOT_ESU2 finished/
mv -f  ./M-M-CZ_Full-CRZ finished/
mv -f  ./A1-A1-CNOT_Full-Pauli-CRZ finished/
mv -f  ./A2_Efficient-CRX finished/
mv -f  ./M-A1-CNOT_HWE-CZ finished/
mv -f  ./A2-A2-CZ_Full-CRZ finished/
mv -f  ./A2-A2-CZ_HWE-CZ finished/
mv -f  ./A1-A1-CZ_Full-Pauli-CRZ finished/
mv -f  ./A2-A2-CZ_Full-Pauli-CRZ finished/
mv -f  ./M-A1-CZ_HWE-CZ finished/
mv -f  ./A1-A1-CZ_HWE-CZ finished/
mv -f  ./A2-A2-CNOT_Full-CRZ finished/
mv -f  ./M-A2-CNOT_Full-CRZ finished/
mv -f  ./M-A2-CNOT_ESU2 finished/
mv -f  ./IQP_Efficient-CRZ finished/
mv -f  ./M-M-CNOT_Full-CRZ finished/
mv -f  ./A2-A2-CNOT_Full-Pauli-CRZ finished/
mv -f  ./M-A1-CZ_Full-Pauli-CRZ finished/
mv -f  ./A2-A2-CNOT_HWE-CZ finished/
mv -f  ./A1-A1-CNOT_Modified-Pauli-CRZ finished/
mv -f  ./A1-A1-CZ_HWE-CNOT finished/
mv -f  ./A2-A2-CZ_Efficient-CRZ finished/
mv -f  ./A2-A2-CNOT_Modified-Pauli-CRZ finished/
mv -f  ./A1_Full-Pauli-CRX finished/
mv -f  ./A1-A1-CNOT_Efficient-CRZ finished/
mv -f  ./M-A1-CNOT_Efficient-CRZ finished/
mv -f  ./M-M-CZ_Full-Pauli-CRX finished/
mv -f  ./A1-A1-CZ_Hadamard finished/
mv -f  ./M_ESU2 finished/
mv -f  ./M-A2-CZ_ESU2 finished/
mv -f  ./IQP_Full-CRX finished/
mv -f  ./M-A2-CNOT_Modified-Pauli-CRZ finished/
mv -f  ./M_Hadamard finished/
mv -f  ./A1_Modified-Pauli-CRZ finished/
mv -f  ./A2_Full-CRX finished/
mv -f  ./A1_Full-CRZ finished/
mv -f  ./M-A2-CZ_Full-Pauli-CRX finished/
mv -f  ./M-A1-CZ_Efficient-CRX finished/
mv -f  ./A2-A2-CNOT_Efficient-CRZ finished/
mv -f  ./A1_Hadamard finished/
mv -f  ./M-M-CZ_HWE-CNOT finished/
mv -f  ./A1-A1-CZ_Efficient-CRZ finished/
mv -f  ./M-A1-CZ_HWE-CNOT finished/
mv -f  ./M_Full-CRZ finished/
mv -f  ./M-M-CNOT_Modified-Pauli-CRZ finished/
mv -f  ./M-M-CNOT_HWE-CNOT finished/
mv -f  ./M-A2-CNOT_Full-Pauli-CRZ finished/
mv -f  ./A1-A1-CNOT_Full-CRX finished/
mv -f  ./M-A2-CZ_Modified-Pauli-CRZ finished/
mv -f  ./M-A2-CNOT_HWE-CNOT finished/
mv -f  ./A2-A2-CNOT_HWE-CNOT finished/
mv -f  ./A2_ESU2 finished/
mv -f  ./A1-A1-CZ_Full-CRZ finished/
mv -f  ./A2-A2-CZ_Modified-Pauli-CRZ finished/
mv -f  ./A2-A2-CZ_HWE-CNOT finished/
mv -f  ./IQP_Modified-Pauli-CRX finished/
mv -f  ./A1-A1-CNOT_HWE-CZ finished/
mv -f  ./M-A1-CNOT_Modified-Pauli-CRZ finished/
mv -f  ./M-M-CNOT_Hadamard finished/
mv -f  ./A2_Full-Pauli-CRZ finished/
mv -f  ./A2-A2-CZ_ESU2 finished/
mv -f  ./M-A2-CNOT_Hadamard finished/
mv -f  ./A2-A2-CNOT_Hadamard finished/
mv -f  ./A2_Modified-Pauli-CRX finished/
mv -f  ./M-A1-CZ_Modified-Pauli-CRX finished/
mv -f  ./A1-A1-CZ_ESU2 finished/
mv -f  ./A2-A2-CZ_Hadamard finished/
mv -f  ./M-A1-CNOT_Full-CRX finished/
mv -f  ./M-M-CZ_Hadamard finished/
mv -f  ./M_Modified-Pauli-CRZ finished/
mv -f  ./A1_HWE-CNOT finished/
mv -f  ./M-M-CZ_Modified-Pauli-CRZ finished/
mv -f  ./M-M-CNOT_Efficient-CRX finished/
mv -f  ./M-A2-CNOT_Efficient-CRX finished/
mv -f  ./M_Full-Pauli-CRX finished/
mv -f  ./A1-A1-CZ_Modified-Pauli-CRX finished/
mv -f  ./A1_Efficient-CRZ finished/
mv -f  ./M_Efficient-CRZ finished/
mv -f  ./IQP_Full-Pauli-CRX finished/
mv -f  ./M-A2-CZ_Efficient-CRX finished/
mv -f  ./M-A1-CZ_Hadamard finished/
