#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5sine_A1_Full-Pauli-CRX
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1_Full-Pauli-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1_Full-Pauli-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/sine5qubits/A1_Full-Pauli-CRX
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/sine5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/sine5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/sine5qubits/A1_Full-Pauli-CRX  --settings /home/gjones/scratch/fivequbit_tests/sine5qubits/A1_Full-Pauli-CRX/A1_Full-Pauli-CRX.json --train_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_train.bin --test_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_test.bin --scaler /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_scaler.bin >> A1_Full-Pauli-CRX.out 2>&1 

cd ..
touch A1_Full-Pauli-CRX.done

