#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5sine_IQP_HWE-CZ
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=IQP_HWE-CZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_HWE-CZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/sine5qubits/IQP_HWE-CZ
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/sine5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/sine5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/sine5qubits/IQP_HWE-CZ  --settings /home/gjones/scratch/fivequbit_tests/sine5qubits/IQP_HWE-CZ/IQP_HWE-CZ.json --train_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_train.bin --test_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_test.bin --scaler /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_scaler.bin >> IQP_HWE-CZ.out 2>&1 

cd ..
touch IQP_HWE-CZ.done

