#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5sine_M_HWE-CNOT
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M_HWE-CNOT.e%J        # The file where run time errors will be dumped
#SBATCH --output=M_HWE-CNOT.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/sine5qubits/M_HWE-CNOT
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/sine5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/sine5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/sine5qubits/M_HWE-CNOT  --settings /home/gjones/scratch/fivequbit_tests/sine5qubits/M_HWE-CNOT/M_HWE-CNOT.json --train_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_train.bin --test_set /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_test.bin --scaler /home/gjones/scratch/fivequbit_tests/sine5qubits/sine_scaler.bin >> M_HWE-CNOT.out 2>&1 

cd ..
touch M_HWE-CNOT.done

