#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5quadratic_A2-A2-CNOT_Full-CRX
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2-A2-CNOT_Full-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2-A2-CNOT_Full-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/quad5qubits/A2-A2-CNOT_Full-CRX
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/quad5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/quad5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/quad5qubits/A2-A2-CNOT_Full-CRX  --settings /home/gjones/scratch/fivequbit_tests/quad5qubits/A2-A2-CNOT_Full-CRX/A2-A2-CNOT_Full-CRX.json --train_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_train.bin --test_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_test.bin --scaler /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_scaler.bin >> A2-A2-CNOT_Full-CRX.out 2>&1 

cd ..
touch A2-A2-CNOT_Full-CRX.done

