#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5quadratic_A2_ESU2
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2_ESU2.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2_ESU2.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/quad5qubits/A2_ESU2
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/quad5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/quad5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/quad5qubits/A2_ESU2  --settings /home/gjones/scratch/fivequbit_tests/quad5qubits/A2_ESU2/A2_ESU2.json --train_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_train.bin --test_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_test.bin --scaler /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_scaler.bin >> A2_ESU2.out 2>&1 

cd ..
touch A2_ESU2.done

