#! /bin/bash
#SBATCH -t 0-12:00:00
#SBATCH -J 5quadratic_M-M-CZ_Efficient-CRZ
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-M-CZ_Efficient-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-M-CZ_Efficient-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/quad5qubits/M-M-CZ_Efficient-CRZ
apptainer run -C -B /home/gjones/scratch/fivequbit_tests/quad5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/quad5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/quad5qubits/M-M-CZ_Efficient-CRZ  --settings /home/gjones/scratch/fivequbit_tests/quad5qubits/M-M-CZ_Efficient-CRZ/M-M-CZ_Efficient-CRZ.json --train_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_train.bin --test_set /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_test.bin --scaler /home/gjones/scratch/fivequbit_tests/quad5qubits/quadratic_scaler.bin >> M-M-CZ_Efficient-CRZ.out 2>&1 

cd ..
touch M-M-CZ_Efficient-CRZ.done

