#! /bin/bash
#SBATCH -t 3-00:00:00
#SBATCH -J 16quadratic_A2_Full-CRX
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A2_Full-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=A2_Full-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/sixteenqubit_test/quad16qubit/A2_Full-CRX

apptainer run -C -B /home/gjones/scratch/sixteenqubit_test/quad16qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/sixteenqubit_test/quad16qubit/main.py --save_path /home/gjones/scratch/sixteenqubit_test/quad16qubit/A2_Full-CRX  --settings /home/gjones/scratch/sixteenqubit_test/quad16qubit/A2_Full-CRX/A2_Full-CRX.json --train_set /home/gjones/scratch/sixteenqubit_test/quad16qubit/quadratic_train.bin --test_set /home/gjones/scratch/sixteenqubit_test/quad16qubit/quadratic_test.bin --scaler /home/gjones/scratch/sixteenqubit_test/quad16qubit/quadratic_scaler.bin >> A2_Full-CRX.out 2>&1 

cd ..
touch A2_Full-CRX.done

