#! /bin/bash
#SBATCH -t 3-00:00:00
#SBATCH -J 16quadratic_M_Full-CRZ
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M_Full-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=M_Full-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/sixteenqubit_test/quad16qubit/M_Full-CRZ

apptainer run -C -B /home/gjones/scratch/sixteenqubit_test/quad16qubit ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/sixteenqubit_test/quad16qubit/main.py --save_path /home/gjones/scratch/sixteenqubit_test/quad16qubit/M_Full-CRZ  --settings /home/gjones/scratch/sixteenqubit_test/quad16qubit/M_Full-CRZ/M_Full-CRZ.json --train_set /home/gjones/scratch/sixteenqubit_test/quad16qubit/quadratic_train.bin --test_set /home/gjones/scratch/sixteenqubit_test/quad16qubit/quadratic_test.bin --scaler /home/gjones/scratch/sixteenqubit_test/quad16qubit/quadratic_scaler.bin >> M_Full-CRZ.out 2>&1 

cd ..
touch M_Full-CRZ.done

