#! /bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -J 5_PCA5_0.8_Morgan_A1-A1-CZ_Efficient-CRZ
#SBATCH -N 1
#SBATCH -n 64
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1-A1-CZ_Efficient-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1-A1-CZ_Efficient-CRZ.o%J               # The file where the output of the terminal will be dumped

cd /home/gjones/scratch/rerun_BSE/5/A1-A1-CZ_Efficient-CRZ

/lustre06/project/6006115/gjones/env/bin/python3 /home/gjones/scratch/rerun_BSE/5/main.py --save_path /home/gjones/scratch/rerun_BSE/5/A1-A1-CZ_Efficient-CRZ  --settings /home/gjones/scratch/rerun_BSE/5/A1-A1-CZ_Efficient-CRZ/A1-A1-CZ_Efficient-CRZ.json --train_set /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_train.bin --test_set /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_test.bin --scaler /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_scaler.bin --save_circuits True --resume_file /home/gjones/scratch/rerun_BSE/5/A1-A1-CZ_Efficient-CRZ/partial_state_model.bin > A1-A1-CZ_Efficient-CRZ.out 2>&1

cd ..
touch A1-A1-CZ_Efficient-CRZ.done

