#! /bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -J 5_PCA5_0.8_Morgan_A1_Efficient-CRX
#SBATCH -N 1
#SBATCH -n 64
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1_Efficient-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1_Efficient-CRX.o%J       # The file where the output of the terminal will be dumped

cd /home/gjones/scratch/rerun_BSE/5/A1_Efficient-CRX

/lustre06/project/6006115/gjones/env/bin/python3 /home/gjones/scratch/rerun_BSE/5/main.py --save_path /home/gjones/scratch/rerun_BSE/5/A1_Efficient-CRX --settings /home/gjones/scratch/rerun_BSE/5/A1_Efficient-CRX/A1_Efficient-CRX.json --train_set /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_train.bin --test_set /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_test.bin --scaler /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_scaler.bin --save_circuits True > A1_Efficient-CRX.out 2>&1

cd ..
touch A1_Efficient-CRX.done
