#! /bin/bash
#SBATCH -t 2-00:00:00
#SBATCH -J 5_PCA5_0.8_Morgan_IQP_Efficient-CRX
#SBATCH -N 1
#SBATCH -n 64
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=IQP_Efficient-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_Efficient-CRX.o%J               # The file where the output of the terminal will be dumped

cd /home/gjones/scratch/rerun_BSE/5/IQP_Efficient-CRX

/lustre06/project/6006115/gjones/env/bin/python3 /home/gjones/scratch/rerun_BSE/5/main.py --save_path /home/gjones/scratch/rerun_BSE/5/IQP_Efficient-CRX  --settings /home/gjones/scratch/rerun_BSE/5/IQP_Efficient-CRX/IQP_Efficient-CRX.json --train_set /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_train.bin --test_set /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_test.bin --scaler /home/gjones/scratch/rerun_BSE/5/PCA5_0.8_Morgan_scaler.bin --save_circuits True --resume_file /home/gjones/scratch/rerun_BSE/5/IQP_Efficient-CRX/final_state_model.bin > IQP_Efficient-CRX.out 2>&1

cd ..
touch IQP_Efficient-CRX.done

