#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 5_DDCC_A1-A1-CZ_HWE-CNOT
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=300           # memory per cpu
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1-A1-CZ_HWE-CNOT.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1-A1-CZ_HWE-CNOT.o%J               # The file where the output of the terminal will be dumped

module load apptainer
cd /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/A1-A1-CZ_HWE-CNOT

apptainer run -C -B /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5 /home/gjones/projects/def-jacobsen/gjones/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/main.py --save_path /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/A1-A1-CZ_HWE-CNOT  --settings /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/A1-A1-CZ_HWE-CNOT/A1-A1-CZ_HWE-CNOT.json --train_set /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/5_DDCC_train.bin --test_set /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/5_DDCC_test.bin --scaler /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/5_DDCC_scaler.bin >> A1-A1-CZ_HWE-CNOT.out 2>&1

cd ..
touch A1-A1-CZ_HWE-CNOT.done

