#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 5_DDCC_M-A1-CNOT_HWE-CZ
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=300           # memory per cpu
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=M-A1-CNOT_HWE-CZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=M-A1-CNOT_HWE-CZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer
cd /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/M-A1-CNOT_HWE-CZ

apptainer run -C -B /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5 /home/gjones/projects/def-jacobsen/gjones/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/main.py --save_path /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/M-A1-CNOT_HWE-CZ  --settings /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/M-A1-CNOT_HWE-CZ/M-A1-CNOT_HWE-CZ.json --train_set /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/5_DDCC_train.bin --test_set /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/5_DDCC_test.bin --scaler /home/gjones/scratch/NARVAL_FINISH/qml_DDCC/5/5_DDCC_scaler.bin >> M-A1-CNOT_HWE-CZ.out 2>&1

cd ..
touch M-A1-CNOT_HWE-CZ.done

