#! /bin/bash
#SBATCH -t 0-23:59:59
#SBATCH -J 0.1_quadratic_IQP_Full-Pauli-CRX
#SBATCH -N 1
#SBATCH -n 80
#SBATCH --account=rrg-fekl-ac
#SBATCH --error=IQP_Full-Pauli-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_Full-Pauli-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer
cd /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1/IQP_Full-Pauli-CRX

apptainer run -C -B /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1 /home/j/jacobsen/gjones/deb.sif /opt/miniconda/bin/python /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1/main.py --save_path /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1/IQP_Full-Pauli-CRX  --settings /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1/IQP_Full-Pauli-CRX/IQP_Full-Pauli-CRX.json --train_set /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1/0.1_quadratic_train.bin --test_set /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1/quadratic_test.bin --scaler /scratch/j/jacobsen/gjones/funct_specific/quadratic/learning_curves/0.1/quadratic_scaler.bin >> IQP_Full-Pauli-CRX.out 2>&1

cd ..
touch IQP_Full-Pauli-CRX.done

