#! /bin/bash
#SBATCH -t 7-00:00:00
#SBATCH -J 3_RUD_PCA5_Morgan_IQP_Full-Pauli-CRZ
#SBATCH -N 1
#SBATCH -n 16
#SBATCH --mem-per-cpu=260M
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=IQP_Full-Pauli-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_Full-Pauli-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD/IQP_Full-Pauli-CRZ
apptainer run -C -B /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD/main.py --save_path /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD/IQP_Full-Pauli-CRZ  --settings /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD/IQP_Full-Pauli-CRZ/IQP_Full-Pauli-CRZ.json --train_set /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD/PCA5_Morgan_train.bin --test_set /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD/PCA5_Morgan_test.bin --scaler /home/gjones/scratch/BSE_RUD_AL_test/5qubit/3_RUD/PCA5_Morgan_scaler.bin >> IQP_Full-Pauli-CRZ.out 2>&1 

cd ..
touch IQP_Full-Pauli-CRZ.done

