#! /bin/bash
#SBATCH -t 1-00:00:00
#SBATCH -J __pycache__
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=__pycache__.e%J        # The file where run time errors will be dumped
#SBATCH --output=__pycache__.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/lin5qubits/__pycache__

apptainer run -C -B /home/gjones/scratch/fivequbit_tests/lin5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/lin5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/lin5qubits/__pycache__  --settings /home/gjones/scratch/fivequbit_tests/lin5qubits/__pycache__/__pycache__.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> __pycache__.out 2>&1 

cd ..
touch __pycache__.done

