#! /bin/bash
#SBATCH -t 1-00:00:00
#SBATCH -J A1-A1-CZ_Efficient-CRX
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=A1-A1-CZ_Efficient-CRX.e%J        # The file where run time errors will be dumped
#SBATCH --output=A1-A1-CZ_Efficient-CRX.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/lin5qubits/A1-A1-CZ_Efficient-CRX

apptainer run -C -B /home/gjones/scratch/fivequbit_tests/lin5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/lin5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/lin5qubits/A1-A1-CZ_Efficient-CRX  --settings /home/gjones/scratch/fivequbit_tests/lin5qubits/A1-A1-CZ_Efficient-CRX/A1-A1-CZ_Efficient-CRX.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> A1-A1-CZ_Efficient-CRX.out 2>&1 

cd ..
touch A1-A1-CZ_Efficient-CRX.done

