#! /bin/bash
#SBATCH -t 1-00:00:00
#SBATCH -J IQP_Modified-Pauli-CRZ
#SBATCH -N 1
#SBATCH -n 12
#SBATCH --account=rrg-jacobsen-ab
#SBATCH --error=IQP_Modified-Pauli-CRZ.e%J        # The file where run time errors will be dumped
#SBATCH --output=IQP_Modified-Pauli-CRZ.o%J               # The file where the output of the terminal will be dumped

module load apptainer 
cd /home/gjones/scratch/fivequbit_tests/lin5qubits/IQP_Modified-Pauli-CRZ

apptainer run -C -B /home/gjones/scratch/fivequbit_tests/lin5qubits ~/deb.sif /opt/miniconda/bin/python /home/gjones/scratch/fivequbit_tests/lin5qubits/main.py --save_path /home/gjones/scratch/fivequbit_tests/lin5qubits/IQP_Modified-Pauli-CRZ  --settings /home/gjones/scratch/fivequbit_tests/lin5qubits/IQP_Modified-Pauli-CRZ/IQP_Modified-Pauli-CRZ.json --train_set /linear_train.bin --test_set /linear_test.bin --scaler /linear_scaler.bin >> IQP_Modified-Pauli-CRZ.out 2>&1 

cd ..
touch IQP_Modified-Pauli-CRZ.done

